---
- name: "Create ssh host key backup directory"
  file:
    path=/mnt/state/_ssh_host_keys
    state=directory
    owner=root
    group=root
    mode=0700

- name: "Preserve ssh host keys"
  action: command cp -a /etc/ssh/ssh_host_* /mnt/state/_ssh_host_keys/
