---
- hosts: "{{ group | default=all }}"
  name: "Rebuild with new image"
  nova_rebuild:
    instance_id: "{{ instance_id }}"
    image_id: "{{ rebuild_image_id }}"
    preserve_ephemeral: true
    delegate_to: localhost
